run:
  # Include test files or not.
  # Default: true
  tests: true
linters:
  enable-all: true
  disable:
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - interfacer
linters-settings:
  tagliatelle:
    # Check the struck tag name case.
    case:
      # Use the struct field name to check the name of the struct tag.
      # Default: false
      use-field-name: false
      rules:
        # Any struct tag type can be used.
        # Support string case: `camel`, `pascal`, `kebab`, `snake`, `goCamel`, `goPascal`, `goKebab`, `goSnake`, `upper`, `lower`
        json:     snake
        yaml:     camel
        xml:      camel
        whatever: kebab
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 131